# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x07\x65xample\"3\n\rAttachSession\x12\x12\n\nsession_id\x18\x01 \x02(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\"\x96\x01\n\x0bUserRequest\x12\x12\n\nsession_id\x18\x01 \x02(\t\x12\x12\n\n_messageId\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\x12\x30\n\x05param\x18\x04 \x03(\x0b\x32!.example.UserRequest.RequestParam\x1a\x1d\n\x0cRequestParam\x12\r\n\x05param\x18\x01 \x01(\t\"}\n\x0eServerResponse\x12\x0c\n\x04\x63ode\x18\x01 \x02(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x32\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32$.example.ServerResponse.ResponseDate\x1a\x1c\n\x0cResponseDate\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ATTACHSESSION']._serialized_start=26
  _globals['_ATTACHSESSION']._serialized_end=77
  _globals['_USERREQUEST']._serialized_start=80
  _globals['_USERREQUEST']._serialized_end=230
  _globals['_USERREQUEST_REQUESTPARAM']._serialized_start=201
  _globals['_USERREQUEST_REQUESTPARAM']._serialized_end=230
  _globals['_SERVERRESPONSE']._serialized_start=232
  _globals['_SERVERRESPONSE']._serialized_end=357
  _globals['_SERVERRESPONSE_RESPONSEDATE']._serialized_start=329
  _globals['_SERVERRESPONSE_RESPONSEDATE']._serialized_end=357
# @@protoc_insertion_point(module_scope)
